config/routes.rb
BeerButton::Application.routes.draw do

  resources :users 
  resources :locations
  resources :pubs

  get 'search' => 'pubs#search'
  get "index" => 'site#index'
  get "about" => 'site#about'
  get "FAQ" => 'site#faq'
  get "privacy" => 'site#privacy'

  post "login" => 'site#login'
  get "logout" => 'site#logout'
  post "signup" => 'site#signup', :as => :signup

  root :to => 'site#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  attr_accessible :name, :brewery

  has_and_belongs_to_many :pubs
  belongs_to :brewery

  validates :name, :length => { :minimum => 1 }


end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  attr_accessible :name, :beers

  has_many :beers
  has_and_belongs_to_many :pubs
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :pubs
  has_many :pubs
  
  

  geocoded_by :address
  after_validation :geocode
end

app/models/pub.rb
class Pub < ActiveRecord::Base
  attr_accessible :name, :breweries, :location, :beers

  has_many :visits
  has_many :users, :through => :visits
  has_and_belongs_to_many :beers
  has_and_belongs_to_many :breweries
  belongs_to :location

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :name_first, :name_last, :password, :password_confirmation

  has_secure_password

  has_many :visits
  has_many :pubs, :through => :visits

  validates :email, :presence => true
  validates :email, :uniqueness => true

  validates_presence_of :password, :on => :create

  before_validation :downcase_email
  
  def downcase_email
    self.email.downcase!
  end

end   

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :visited_on, :user, :pub

  belongs_to :user
  belongs_to :pub
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  # This action lists all locations (it acts on the collection)
  def index
    @locations = Location.all
  end

  # This action shows the detail of an individual location (it acts on the member of the collection)
  # so we must provide an id
  def show
    @location = Location.find(params[:id])
  end

  # This action shows a form for adding new members, so it must act on the collection (we don't have a member yet)
  def new
    @location = Location.new
  end

  # This action creates a new location and then redirects to index probably (or show), so it acts on the collection
  # (adding a new member to it)
  def create
    @location = Location.new(params[:location])
  end

  # This action shows a form for editing a location, so we must provide the member id (it acts on a member)
  def edit
    @location = Location.find(params[:id])
  end

  # This action updates a location and then redirects to index probably (or show), so it acts on a member
  # and we must proived that member's id
  def update
    @location = Location.find(params[:id])
    @location.update_attributes(params[:location])
  end

  # This action deletes a location and then redirects to index, so it acts on a member and needs the id
  def destroy
    @location = Location.find(params[:id])
  end
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
  def index
    @pubs = Pub.all
  end

  def show
    @pub = Pub.find(params[:id])

    @lat = @pub.location.latitude
    @long = @pub.location.longitude

    
  end

  def search
    @locations = Location.near(params[:address]).includes(:pubs).limit(5)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locations, :include => [:pubs] }
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @user = User.new
  end

  def about
  end

  def FAQ
  end

  def privacy
  end

  def signup
    @user = User.new(params[:user])

    if @user.save
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def login
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      @user = User.new
      render :index
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
  
    <%= link_to "Home", root_path, :class => 'brand' %>
  
  
    
  
  
    <%= link_to "Watering Holes", pubs_path, :class => 'brand' %>
  



    <div class="login offset6">
        <% if current_user %>
            <p class="sponsored">You&rsquo;re logged in as <%= current_user.name_first %> <%= current_user.name_last %> <%= link_to 'Log out', logout_path %></p>
        <% else %>
          <form class="smooth" method="post" action="/login">
            <input type="text" name="email" placeholder="Email" class="field">
            <input type="password" name="password" placeholder="Password" class="field">
            <input type="submit" name="Login" value="Login" class="btn btn-primary">
          </form>
        <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "The Beer Button" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
    <%= yield(:head) %>
  </head>
  <body>
    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjA-5BpTBSF5bxSleR0G1tmvK0a15LtB4&sensor=false">
    </script>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <!--<div id="main" role="main"> background test comment-->
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <div class="row">
                <h1 class="span4 offset4 logo"> The Beer Compass</h1>
              </div>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    <!-- </div> Just see what this is here for.-->  <!--! end of #main -->
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  

  <div class="actions">
    <%= f.submit :class => 'btn btn-danger' %>
  </div>


<% end %>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

<% @locations.each do |location| %>

  <%= link_to location.address, location_path(location) %>

<% end %>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>

app/views/locations/show.html.erb
<h1><%= @location.address %></h1>

<% @location.pubs.each do |pub| %>
  <%= pub.name %><br />
  <%= pub.location.address %>
<% end %>

app/views/pubs/index.html.erb
<h1>Here lies a mighty list-o-pubs.</h1>
<h1>Click the letter view the corresponding watering holes</h1>
<!--<p>Find me in app/views/pubs/index.html.erb</p> -->

<% ('A'..'Z').to_a.each do |c| %>
  <h2 class="indexer" data-indice="<%= c %>"> <%= c %> </h2>
<% end %>

<!-- The Alphabets -->
<% ('A'..'Z').to_a.each do |c| %>
  <div id="cat_<%= c %>" class="index-category"<% if c != 'A' %> style="display:none"<% end %>>
    <div class="row"><div class="span12"><h1> <%= c %> </h1></div></div>
    <div class="row">
      <div class="span3">
        <ul>
          <% inpub = @pubs.select { |f| (c.downcase) === f.name.first.downcase} %>
          <% num_per_col = (inpub.length / 4) + 1 %>
          <% inpub.each_with_index do |pub, index| %>
            <% if index % num_per_col == 0 && index != 0 %>
                </ul>
              </div>
              <div class="span3">
                <ul>
            <% end %>
              <li> <%= link_to pub.name, pub_path(pub) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<script>


</script>

app/views/pubs/search.html.erb
<h1>Your Nearest Pubs</h1>

<div class="row">
  <div class="span2">
    <% @locations.each do |location| %>

      <% location.pubs.each do |pub| %>
       <h4 class="pub_title"> <%= pub.name %> </h4>
       <p class="pub_address"> <%= pub.location.address %> </p>
      <% end %>
    <% end %>
  </div>
  <div id="map-canvas" class="span8 offset1 map" data-address="<%= params[:address] %>"></div>
</div>

app/views/pubs/show.html.erb
<div class="row">
  <div class="span4">
    <h1><%= @pub.name %></h1>
    <h3><%= @pub.location.address %></h3>
  </div>
  <div class="span6">
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@pub.location.latitude}%2C#{@pub.location.longitude}" %>
  </div>
</div>


    





   


  

app/views/site/FAQ.html.erb
<h1>Site#FAQ</h1>
<p>Find me in app/views/site/FAQ.html.erb</p>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/index.html.erb
<p style="text-align: center"> Stick a location in the box to find your nearest pubs </p>
<div class="row">
  <div class="span12 mainbanner">
    <%= image_tag 'tap_heads.jpg' %>
    <div class="span3 beer_def">
    <p>beer  (bîr)
      n.
      1.
      a. A fermented alcoholic beverage brewed from malt and flavored with hops.
      2. A serving of one of these beverages.
    </p>
  </div>
    <div class='span3 pub_def'>
      <p>A pub (pron.: /pʌb/), formally public house (a house "open to the public", as opposed to a private house), is a drinking establishment fundamental to the culture of Britain, Ireland, Australia, Canada and New Zealand</p>
    </div>
    
      <div class="beer_form span4 offset3">
        <form method="get" action="/search">
        <input type="search" name="address" placeholder="Where are you?...">
        <input type="submit" name=" Find My Pubs " class="btn btn-info">
      </form>
  </div>

  </div>
  
  
</div><!--mainpic-->


<div class="row">
    <div class="span6 offset1">
      <h1 id="clicksign"> Click me to Register </h1>
        <div id="signup" class="start_hidden">
          <%= form_for @user, :url => signup_url do |f| %>
            <p class="field"><%= f.text_field :name_first, :placeholder => 'First name' %></p>
            <p><%= f.text_field :name_last, :placeholder => 'Last name' %></p>
            <p><%= f.text_field :email, :placeholder => 'Email address' %></p>
            <p><%= f.password_field :password, :placeholder => 'Password' %></p>
            <p><%= f.password_field :password_confirmation, :placeholder => 'Confirm password' %></p>
            <p><%= f.submit "Hit me", :class => 'btn btn-primary' %></p>
          <% end %>
        </div>
    </div>
  <div class="span4">
    <br><!--just until you sort the padding and layout, purely for bootstrap ref -->
    <h4> Pub of the week: The Dovetail </h4>
    <article>
      <p>A tucked away little gem, serving an plethora of Belgian beers with a smile. Whether you are looking for a Flemish sour ale, a Trappist dubbel or having taken leave of your taste buds and order a beer brewed with banana, this is the place for you. Beer sponge *sorry* food isn't bad either. </p>
      <p id="easteregg" class="clickable"> Address: 9-10 Jerusalem Passage  City of London, London, Greater London EC1V 4JP </p>
        <div id="reveal" class="hider">
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=370x200&sensor=false&zoom=16&markers=51.52317,-0.10401" %>
        </div>
    </article>
  </div>
</div>

app/views/site/privacy.html.erb
<h1>Site#privacy</h1>
<p>Find me in app/views/site/privacy.html.erb</p>

TEST